### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by Voltir** [lihaoyi/scala.rx#102]
Need to update the README with 0.4.0 changes, possibly including examples of the new "imap and friends" functionality on `Var`s. @fdietze is there anything else you wanted to put in to 0.4.0?

**Comment by fdietze** [comment]
I'm fine with the features for 0.4.0. My most important points were the bidirectional var operators and fixing flatMap.

I'm a bit concerned, if we really should pull in Monocle as a dependency. Having a type-class for lenses which we could use would be much nicer. Any ideas?

**Comment by fdietze** [comment]
We should also investigate if Rx.Dynamic could be made covariant again.

**Comment by Voltir** [comment]
I think I'm ok with the monocle dependency - I think I want access to the Iso typeclass in other libs and monocle seems to be the most standard way to get there without going "full scalaz".

**Comment by Andrei-Pozolotin** [comment]
please start releasing more frequently

**Comment by Andrei-Pozolotin** [comment]
please maintain release tags

**Comment by fdietze** [comment]
@Andrei-Pozolotin Please be more concrete about what exactly you expect and consider to contribute.

**Comment by fdietze** [comment]
I think feature-wise we are ready to release. What do you think?

**Comment by Voltir** [comment]
Sure, we should cut a release - ill reach out to @lihaoyi

**Comment by Voltir** [comment]
Published
