### ISSUE TITLE
scalarx 0.4.0 for Scala 2.11 not published?

### ISSUE THREAD

**Issue by ThijsBroersen** [lihaoyi/scala.rx#117]
Has the publication of the package for Scala 2.11 been overlooked? I noticed the new version of scala.rx and my 2.11 projects can't find the artifact. I tried testing and compiling the master branch.. all successful!

**Comment by Voltir** [comment]
Ah, sorry - I only published the 2.12 artifacts - ill see what I can do about 2.11

**Comment by j-keck** [comment]
Is it now cross-published for 2.11?

2.11 is necessary for Scala on Android Projects.

**Comment by Voltir** [comment]
The 2.11 artifacts should be published now.

**Comment by j-keck** [comment]
Thanks!
