### ISSUE TITLE
Example from README does not compile

### ISSUE THREAD

**Issue by JohnReedLOL** [lihaoyi/scala.rx#119]
This example does not compile: https://i.imgur.com/Ra1zOGD.png

See: https://i.imgur.com/eif1gfT.png

**Comment by fdietze** [comment]
Thanks for reporting.

`Rx.unsafe` is defined private here:

https://github.com/lihaoyi/scala.rx/blob/master/scalarx/shared/src/main/scala/rx/Rx.scala#L114

Should we make it public again?
