### ISSUE TITLE
some helpers for reactive collections

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/scala.rx#12]
I am using scala react for databiding in my scalajs app. It is easy to use in case of binding to particular values but it is not clear for me how to make collections reactive.

Consider I have something like:
val myCollection:Var[Map[String,MyCaseClass]]

and I have to update DOM when there are some changes there. In such case I have to make something like  myCollection.reduce(updatehandler _) that would compare old and new versions and be used by Observer that will react on changes ( move elements in dom tree, delte from DOM, add to dom)

I think that this usecase is very common (not only for scalajs but in other cases when we want to look what changes in collections happened and react) to make some helpers for that.

In the same time I am not sure how to implement it right. The most stratiforward approach is to iterate whole collection and produce Inserted/Deleted/Moved events that would include elements that changed. But maybe there is a better way for this?

**Comment by lihaoyi** [comment]
0.3.0, and declaring bug bankruptcy.
