### ISSUE TITLE
some helpers (or docs) to tweak propogation

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/scala.rx#13]
I wonder is there a way to tweak how propagation works?
In my case I want to avoid propagation if the same values are pushed to creatives (for instance fooVar equals 1 and want to avoid propogation if I do fooVar()=1) globably (without a need to say something like val bar = fooVar.filter(v=>v!=fooVar.now) for each reactive variable

**Comment by lihaoyi** [comment]
Propagation is no longer tweakable in 0.3.0
