### ISSUE TITLE
Repository Access

### ISSUE THREAD

**Issue by fdietze** [lihaoyi/scala.rx#131]
Hi @lihaoyi and @Voltir, would it be possible to grant merge access to me @fdietze and @cornerman? We contributed a lot to this repo already and managing the unmerged PRs is a bit hairy.

We could introduce the rule that for a PR to be merged, it needs at least one approval of another maintainer.

What do you think?

**Comment by Voltir** [comment]
Im ok with that

**Comment by lihaoyi** [comment]
sent you an invite

**Comment by fdietze** [comment]
Thank you!
