### ISSUE TITLE
2.13 support

### ISSUE THREAD

**Issue by aginiewicz** [lihaoyi/scala.rx#137]
Hi! Is there some roadmap for 2.13 support?

**Comment by fdietze** [comment]
I tried once, but I wasn't able to get the macros working. @cornerman?

**Comment by mathieuleclaire** [comment]
Hi, 
is a 2.13 version is scheduled ?
Thanks
Mathieu

**Comment by fdietze** [comment]
There is a branch. But I didn't find the time to work on it further: https://github.com/lihaoyi/scala.rx/pulls
If you have the time, see if you can finish it.
