### ISSUE TITLE
add more combinators

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/scala.rx#14]
I think lack of coordinators (in comparison to Reactive extensions) is one of the weakest points of ScalaRx and it is hard to extend them as most of the classes are marked as private or protected (in comparison to Reactive Extensions where there are a lot of methods I can use) there. For instance I want to make reactive that compares current and previous results and maps it to a new Type. Current Reducer does not allow mapping so I have to write my own, but most of the classes that current reducer uses are private so I cannot use them outside of Scala React =(

**Comment by lihaoyi** [comment]
bug bankruptcy: 0.3.0 is out and it's a whole new world!
