### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by cornerman** [lihaoyi/scala.rx#159]
There have been some bug fixes and updates after the last release `0.4.0`. How about we make a new release `0.4.1` now?

In the best case, we wait for scala 2.13 support form #138

**Comment by fdietze** [comment]
Just merged #138, so it would be a good time for a new release.

**Comment by mathieuleclaire** [comment]
+1

**Comment by fdietze** [comment]
@Voltir you have the release permissions, correct?

**Comment by Voltir** [comment]
@fdietze Ah, I still have the credentials somewhere - i havent cut a release in a long time though. Do you need me to do that or should we get @lihaoyi  to grant your release permissions as well?

**Comment by fdietze** [comment]
Both would work for me.

**Comment by Voltir** [comment]
Ok, I remembered how to publish - 0.4.1 for scala 2.12 should be published shortly.. not sure if 2.13 was published though.

**Comment by Voltir** [comment]
Ok, I figured out the 2.13 issue as well, it should be published - I think we can close this issue :)

**Comment by fdietze** [comment]
Awesome, thank you!
