### ISSUE TITLE
add Var.update { oldValue => newValue }

### ISSUE THREAD

**Issue by yanns** [lihaoyi/scala.rx#16]
It would be great if we could update a Var in one function in atomic style.
The current update does not deliver the current value, leading to such code:
```scala
val model = Var("world")
model.update {
  val v = model()
  v.toUpperCase
}
```

It would be easier to write:
```scala
val model = Var("world")
model.update { v =>
  v.toUpperCase
}
```
Or
```scala
val model = Var("world")
model.update(_.toUpperCase)
```

**Comment by lihaoyi** [comment]
Parallelism and thread-safety is now gone; 0.3.0 is totally only single-thread-safe
