### ISSUE TITLE
To scalajs 1.0.1

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/scala.rx#164]
Hi,
I gave a try to upgrade to scalajs 1.0. 
It seems that with utest and monocle upgrades are OK. Your bench, @fdietze, seems to be the final stone to be added to complete the scalajs 1.0. Do you think it is doable (I saw your revert sadly :( ) ?

Mathieu

**Comment by fdietze** [comment]
Sorry, no time right now. Feel free to make a PR on bench, and I'll merge quickly.

**Comment by cornerman** [comment]
Bench is only needed for local testing, so maybe we can get around supporting scalajs 1.0 somehow? It is not needed for the release :)

**Comment by vaclavsvejcar** [comment]
AFAIK bench depends on https://github.com/lihaoyi/autowire, which is not ready for 1.0 as well.

**Comment by fdietze** [comment]
@vaclavsvejcar I guess you're having a different library in mind. My bench library has only `collection-compat` and `minitest` as dependencies:

https://github.com/fdietze/bench/blob/master/build.sbt#L40

**Comment by vaclavsvejcar** [comment]
@fdietze Oh sorry, you're right, my fault :)

**Comment by mathieuleclaire** [comment]
@fdietze I had a look to bench. It seems to me that only a version of minitest for scala-js 1.0 is missing.

**Comment by mathieuleclaire** [comment]
Minitest has been realeased.% ! I did a PR with minitest 2.8.2 for bench @fdietze .

**Comment by fdietze** [comment]
@mathieuleclaire thanks, merged.

**Comment by fdietze** [comment]
PR ist merged. @Voltir could you make another release, please? :pray:

**Comment by Voltir** [comment]
Done :)
