### ISSUE TITLE
Introductory example misses the point

### ISSUE THREAD

**Issue by geggo98** [lihaoyi/scala.rx#19]
The first example on the readme.md does not deliver the point what is so great about Scala.RX. We had the following [dicussion on stackoverflow](http://stackoverflow.com/questions/24484450/what-is-the-difference-between-reactive-programming-and-plain-old-closures) where the too simple example confused a user into thinking Scala.RX is about memoization.

Please consider to update example, so it shows asynchronous notifications. Of course you can use the example I have provided on SO:

```scala
import rx._
import rx.ops._

val a = Var(1); val b = Var(2)
val c: Rx[Int] = Rx{ a() + b() }

val o = c.foreach{value =>
  println(s"c has a new value: ${value}")
}

a()=4
b()=12
a()=35
```

which prints

```
c has a new value: 3 
c has a new value: 6 
c has a new value: 16 
c has a new value: 47
```

**Comment by lihaoyi** [comment]
Lifecycles have changed, feel free to send a PR to docs that @Voltir can argue over or merge
