### ISSUE TITLE
Obs are not linked by strong references to Var and are therefore GCed

### ISSUE THREAD

**Issue by romainreuillon** [lihaoyi/scala.rx#21]
Obs set on Vars are being garabage colected while the observed Var isn't. Is it normal ? I would think that an observable set on a Var should have the same lifecycle as the observed Var.

For example, this code has different behaviour wether we call System.gc or not:

```scala
object Test extends App {

  val l: Seq[Var[Int]] =
    (0 until 10).map { v => Var(v) }


  l.foreach {
     v => Obs(v) { println("observed " + v()) }
  }

  System.gc() // changes the code behaviour

  l.head() = 9

}
```

Is the user suposed to keep strong ref to the Obs he defines ?

**Comment by lihaoyi** [comment]
No more weak refs in 0.3.0
