### ISSUE TITLE
Observe multiple Rx's

### ISSUE THREAD

**Issue by PkmX** [lihaoyi/scala.rx#26]
Let's say we have three `Rx`s and we want to perform side-effects when any of them changes:

    val va = Var(0)
    val vb = Var(0)
    val vc = Var(0)
    for { a <- va ; b <- vb ; c <- vc }
      effectful(a, b, c)

This obviously doesn't work since this creates a new `Obs` every time `va` or `vb` changes.

Currently I'm resorting to creating a `Rx` that bundles all `Rx`s into a tuple, and then create an `Obs` from it:

    for { (a, b, c) <- Rx { (va(), vb(), vc()) } }
      effectful(a, b, c)

While this works, it seems to me that it is a pretty inelegant solution. Is there any possibility to provide a combinator or a better abstraction for this pattern? I believe this is a very common pattern and the library should provide an easy way to solve that.

Thanks.

**Comment by mkotsbak** [comment]
This would be better if there was a zip(), see #46:

```
val va = Var(0)
val vb = Var(0)
val vc = Var(0)
va.zip(vb, vc).foreach(effectful.tupled)
```

**Comment by antonkulaga** [comment]
Why not va.zip(vb)?

**Comment by mkotsbak** [comment]
My example was for observing 3 Var/Rx's. For just va and vb, va.zip(vb) would be nice.

The reason to have that other version is that va.zip(vb).zip(vc) is giving a nested tuple, which is harder to handle later. That is why we hard coded support for more than 2 input channels in MetaRx: https://github.com/MetaStack-pl/MetaRx/blob/d35ee24afaaa49ee044a1d991d2c096c7acbffed/shared/src/main/scala/pl/metastack/metarx/Channel.scala#L134

**Comment by lihaoyi** [comment]
Let's close this in favor of https://github.com/lihaoyi/scala.rx/issues/46
