### ISSUE TITLE
Performance is terrible

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/scala.rx#27]
Benchmarks (https://groups.google.com/forum/#!topic/scala-js/3KixczxoxCU) show that for simple propagators, it takes 5-10x as long to propagate a change as it takes to initialize the graph. To a large extent this defeats the purpose of using change propagation in the first place. When I end up rewriting this, I need to fix it.

**Comment by antonkulaga** [comment]
Is it also relevant for 0.3 version? I am thinking about switching to it if it is stable and faster

**Comment by lihaoyi** [comment]
In theory yes, in practice I haven't benchmarked

**Comment by lihaoyi** [comment]
0.3.0 is way better
