### ISSUE TITLE
Var to readOnly Rx method

### ISSUE THREAD

**Issue by bblfish** [lihaoyi/scala.rx#38]
Sometimes one part of the code wants read/write access, but it only wants other part of the code to get read/access with the ability to observe. It would be useful if one could transform a `Var` to an `Rx` in such a way that it cannot be downcast back to the `Var`.

**Comment by bblfish** [comment]
Ah this probably solves it

```scala
val a: Var = ???
Rx{ a() }
```

**Comment by ngbinh** [comment]
This is probably better:
```scala
val a: Var[T] = ???
a.asInstanceOf[Rx[T]]
```
as `Var` is a subclass of  `Rx`

**Comment by bblfish** [comment]
@ngbinh yes, but then A could be changed by the client later with

```scala
 val a : Rx[T] = fetch(...)
a.asInstanceOf[Var[T]]
```

I am doing this in my own code at the moment, as I control all of it. But the previous answer ( `Rx{ a() }` ) would be more secure, right?

**Comment by ngbinh** [comment]
secure in what sense? If someone has access to your library, he can cast `a` back to `Var`. Yes! But once everything compiles into final binaries (jar, js) then casting approach is safe. 

The downsize of wrapping `Var` with a `Rx` is that you introduce another node on the Rx graph.

**Comment by bblfish** [comment]
Ah yes. So perhaps there could be a method that disables the write part of an `Var` without creating a new node in the `Rx` graph?

**Comment by lihaoyi** [comment]
wait if you are considering reflection then people can always just reflect on the rx and get the var, or people can use sun.mix.unsafe to set bytes anywhere in the process memory. So there's nothing we can do anyway

**Comment by bblfish** [comment]
Well I am just thinking of safety in the way one speaks of not having objects leak information.  That is why there are private variables, or some objects copy information, or why some objects have getters but no setters. So for example if you have an object that has getters and setters but a library wants to disable the setters it can wrap the object in one with the same methods minus the setters. 

As for introspection there are security restrictions on when that is allowed.

**Comment by lihaoyi** [comment]
If you're allowing casting to supertypes as part of your standard usage, god help you ^_^ that breaks every method of OO or FP abstraction that was ever invented

**Comment by bblfish** [comment]
I suppose you mean casting to subtypes. But that is of course done all the time with things like

```scala
some match {
   case None => f()
   case Some(x) => g(x)
}
```

where both `Some` and `None` are subtypes of `Option`

**Comment by lihaoyi** [comment]
Those are for sealed ADTs and not in the general case. I'm not going to
wrap everything just because you can cast things, since even if I wrap it
you can use reflection, and even if you security manager it there are
sufficient ways to break out. If you want runtime protection against
yourself implement your own wrapper, its easy enough ^_^

**Comment by bblfish** [comment]
Yes, I was not really that concerned about that type of security but clarity of APIs. Since an `Rx` can be downcast to a `Var` serving an `Rx` can make a user think of a pattern matching statement, and in my case each `Rx` would be downcastable. So I was more concerned about building a clean and yet efficient API
