### ISSUE TITLE
Change Var[T] covariant

### ISSUE THREAD

**Issue by pocorall** [lihaoyi/scala.rx#41]
Current implementation of `Var[T]` looks more natural to be covariant, and it is needed for my use case.

* Is there any restriction to prevent this change?

**Comment by HerringtonDarkholme** [comment]
@pocorall Given the implementation https://github.com/lihaoyi/scala.rx/blob/master/scalarx/shared/src/main/scala/rx/core/Core.scala#L136
`Var` is not immutable, and `update` method have T in contravariant position.
So I think maybe creating a new `Var` is more suitable.

**Comment by pocorall** [comment]
Oh I missed that point. Then it couldn't be covariant. Thank you.
