### ISSUE TITLE
Operator support

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/scala.rx#44]
Would be nice if this:

```scala
val a = Var(1); val b = Var(2)
val c = Rx{ a() + b() }
```
could be written as:

```scala
val c =  a + b
```

See how it is implemented in MetaRx: https://github.com/MetaStack-pl/MetaRx/blob/master/shared/src/main/scala/pl/metastack/metarx.scala#L49

**Comment by Voltir** [comment]
I don't think I want to do that. I kind of like the readability of knowing when I am dealing in Rx land.

**Comment by antonkulaga** [comment]
I agree with @Voltir , such pluses can lead to confusal

**Comment by mkotsbak** [comment]
Well, it could be up to the user to decide if it is implemented in separate extension class that must explicitly imported.

**Comment by lihaoyi** [comment]
Not gonna happen as far as I can tell
