### ISSUE TITLE
Throttle support

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/scala.rx#45]
See the functionality in Knockout.js: http://knockoutjs.com/documentation/rateLimit-observable.html and in MetaRx: https://github.com/MetaStack-pl/MetaRx/commit/4cc7930e7b0c9b423d33a94868d19be5cf6f1a58

It should ensure that the latest value always is propagated.

**Comment by Voltir** [comment]
I think that this is implemented as debounce?

**Comment by mkotsbak** [comment]
You are completely right it seems, thanks.
