### ISSUE TITLE
Missing code in Readme

### ISSUE THREAD

**Issue by Giymo11** [lihaoyi/scala.rx#59]
In the section where the Timer is explained, the text below the example references a for-loop that does not exist (line 666 I believe)

**Comment by Voltir** [comment]
LoL, signed into the wrong account..

**Comment by Giymo11** [comment]
It's not like it's a big deal, I just happened to stumble upon it and thought I'd mention it ;)

**Comment by Giymo11** [comment]
This was fixed in e06c486937c646d7daaf8626ac10380237c0922b.
