### ISSUE TITLE
Confusion about the behavior of for-loop / flatMap

### ISSUE THREAD

**Issue by fdietze** [lihaoyi/scala.rx#79]
When first using `for`-syntax on `Rx`, it seemed to work the same as with combining them in `Rx{}`. But they behave differently when using a diamond-shape flow-graph:
```
          b
        /   \
source a     o trigger
        \   /
          c
```

Here is an example code:

```scala
println("initializing...")
val rxa = Var(2)
val rxb = rxa.map(_ + 1)
val rxc = rxa.map(_ + 1)
for (
  b <- rxb;
  c <- rxc
) {
  println(s"  for loop triggered: $b, $c")
}
Rx {
  val b = rxb()
  val c = rxc()
  println(s"  rx triggered: $b, $c")
}
println("initialization done")
println("set rxa to 12...")
rxa() = 12
println("set rxa to 22...")
rxa() = 22
println("set rxa to 32...")
rxa() = 32
```

And here the printed result:
```
initializing...
  for loop triggered: 3, 3
  rx triggered: 3, 3
initialization done
set rxa to 12...
   rx triggered: 13, 13
   for loop triggered: 13, 13
   for loop triggered: 3, 13
 set rxa to 22...
   rx triggered: 23, 23
   for loop triggered: 23, 23
   for loop triggered: 13, 23
   for loop triggered: 3, 23
 set rxa to 32...
   rx triggered: 33, 33
   for loop triggered: 33, 33
   for loop triggered: 13, 33
   for loop triggered: 3, 33
   for loop triggered: 23, 33
```

The for-loop prints for every individual change of a,b and itself, while the Rx-version only prints when the calculation wave has finished. Even more, the for-loop leaks Observers for b. This looks like a bug to me. Shouldn't the for-loop ideally behave exactly like the Rx-version?

**Comment by fdietze** [comment]
I'm in favor of either removing `flatMap` altogether or implement it to behave exactly like the `Rx { ... }`. What do you think?

**Comment by Voltir** [comment]
I don't think I want to get rid of flatmap - I like the monadic composition. But yea, leaking observers is not good. Any ideas on how we might fix `for` ? Looks like it might be problematic because it doesn't actually have its own enclosing Rx context.
