### ISSUE TITLE
Bidirectional Var Operators

### ISSUE THREAD

**Issue by fdietze** [lihaoyi/scala.rx#93]
If I invest the time to prepare a PR for my [simplification of Rx](https://github.com/fdietze/duality/blob/master/duality/shared/src/main/scala/rx/Rx.scala) which allows the implementation of some [bidirectional `Var` operators](https://github.com/fdietze/duality/blob/master/duality/shared/src/test/scala/rx/TransformedVarTests.scala), would it be merged? @Voltir?

The `Rx` simplification removes the `Internal` trait of `Rx` and makes its members `private[rx]` instead.

**Comment by Voltir** [comment]
Ok, the monocle stuff looks pretty cool :)

Id like the compile time tests to still work (along with blackbox macros), but yea - id merge it.
